name: Release Go Binary

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -o aur-up main.go

      - name: Generate SHA256 checksum
        run: sha256sum aur-up > aur-up.sha256

      - name: Upload Release Asset (Binary)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./aur-up
          asset_name: aur-up
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Checksum)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./aur-up.sha256
          asset_name: aur-up.sha256
          asset_content_type: text/plain
